start cmd /c python FBXProcessor.py 1
start cmd /c python FBXProcessor.py 10
start cmd /c python FBXProcessor.py 20
start cmd /c python FBXProcessor.py 30
start cmd /c python FBXProcessor.py 40
start cmd /c python FBXProcessor.py 50
start cmd /c python FBXProcessor.py 60
start cmd /c python FBXProcessor.py 70
start cmd /c python FBXProcessor.py 80
start cmd /c python FBXProcessor.py 90
start cmd /c python FBXProcessor.py 100